server:
  port: ${PORT:9080}
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

spring:
  application:
    name: my-event-store-command
  jackson:
    serialization:
      write_dates_as_timestamps: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: ${app.management.base-path:/actuator}
  server:
    servlet:
      context-path: ${app.management.base-path:/actuator}

eureka:
  instance:
    prefer-ip-address: true
#    status-page-url-path: ${management.server.servlet.context-path}/info
    status-page-url-path: /info
#    health-check-url-path: ${management.server.servlet.context-path}/health
    health-check-url-path: /health
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: 'http://admin:password@localhost:8761/eureka'

---
spring:
  config:
    activate:
      on-profile: camel-kafka
  kafka:
    admin:
      client-id: my-event-store-command-admin
    bootstrap-servers: localhost:9092

grpc:
  enabled: true
  shutdownGrace: 1
  port: 6565

logger.level:
  org.apache.kafka: INFO
  com.example.eventstore.command: INFO
  org.springframework.cloud.stream: INFO

logging:
  level:
    root: info
