server:
  port: ${server_port:8761} # Indicate the default PORT where this service will be started
spring:
  rabbitmq:
    #    addresses: mustang.rmq.cloudamqp.com
    addresses: localhost
    #    password: bY0yd8xJR5hsXjfKgf-5JtOpPYhsZd-t
    password: guest
    #    username: fxzoezee
    username: guest
    #    virtual-host: fxzoezee
    virtual-host: vhost_dennis
    port: 5672
  zipkin:
    sender:
      type: rabbit
    base-url: "http://localhost:9411/"
    sleuth:
      sampler:
        probability: 1
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false   #telling the server not to register himself in the service registry
    fetchRegistry: false
    service-url:
      defaultZone: "http://admin:password@${eureka.instance.hostname}:${server.port}/eureka/"   # This is not needed if registerWithEureka: false
  server:
    waitTimeInMsWhenSyncEmpty: 10

management:
  endpoints:
    web:
      base-path: ${app.management.base-path:/actuator}
  server:
    base-path: ${app.management.base-path:/actuator}

#logging:
#  level:
#    org.springframework.cloud: DEBUG
#    org.springframework.web: DEBUG
#    org.springframework: INFO
#  pattern:
#    level: "%d{ABSOLUTE} [%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
