server:
  port: ${webapp.port:8765}

# Pls note that, local rabbitmq need to have host mapping (E.g: 127.0.0.1 localhost
spring:
  application:
    name: my-api-gateway
  rabbitmq:
    #    addresses: mustang.rmq.cloudamqp.com
    addresses: localhost
    #    password: bY0yd8xJR5hsXjfKgf-5JtOpPYhsZd-t
    password: guest
    #    username: fxzoezee
    username: guest
    #    virtual-host: fxzoezee
    virtual-host: vhost_dennis
    port: 5672
  zipkin:
    sender:
      type: rabbit
    base-url: "http://localhost:9411/"
    sleuth:
      sampler:
        probability: 1
  jmx:
    unique-names: true
#  cloud:
#    gateway:
#      routes:
#        - id: queryModule
#          uri: lb://my-event-store-query
#          predicates:
#          - Path=/query/**
#        - id: eventStoreModule
#          uri: lb://my-event-store
#          predicates:
#            - Path=/event-store/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: ${app.management.base-path:/actuator}
  server:
    base-path: ${app.management.base-path:/actuator}

eureka:
  client:
    service-url:
      defaultZone: 'http://admin:password@localhost:8761/eureka'
  instance:
    prefer-ip-address: true
    #    status-page-url-path: ${management.server.servlet.context-path}/info
    status-page-url-path: /info
    #    health-check-url-path: ${management.server.servlet.context-path}/health
    health-check-url-path: /health
    lease-renewal-interval-in-seconds: 1

logging:
  level:
    org.springframework.cloud: INFO
    org.springframework.web: INFO
    org.springframework: INFO
  pattern:
    level: "%d{ABSOLUTE} [%X{X-B3-TraceId}/%X{X-B3-SpanId}] %-5p [%t] %C{2} - %m%n"
